name: 'git-discord-webhook'
description: 'This GitHub Action sends  fancy and more meaningful discord messages for your commits. It includes Test results and coverage.'

inputs:
  webhook_url:
    description: Discord webhook URL
    required: true
  status:
    description: Set it to job.status
    default: ${{ job.status }}

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: check-circle
  color: blue
