name: 'git-discord-webhook'
description: 'This GitHub Action sends  fancy and more meaningful discord messages for your commits. It includes Test results and coverage.'

inputs:
  webhook_url:
    description: Discord webhook URL
  status:
    description: Set it to job.status

runs:
  using: 'docker'
  image: 'action.Dockerfile'

branding:
  icon: check-circle
  color: blue
