name: 'git-discord-webhook'
description: 'This GitHub Action sends  fancy and more meaningful discord messages for your commits. It includes Test results and coverage.'

inputs:
  webhook_url:
    description: Discord webhook URL
  status:
    description: Set it to job.status
  censor_username:
    description: Hide the full GitHub username
    default: false
  hide_links:
    description: Toggle whether to show repo links on the webhook event
    default: false

runs:
  using: 'docker'
  image: 'action.Dockerfile'

branding:
  icon: check-circle
  color: blue
